apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ext-remediation
  labels:
    rbac.ext-remediation/aggregate-to-ext-remediation: "true"
rules:
  - apiGroups:
      - fence-agents-remediation.medik8s.io
    resources:
      - fenceagentsremediationtemplates
    verbs:
      - get
  - apiGroups:
      - fence-agents-remediation.medik8s.io
    resources:
      - fenceagentsremediations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
