apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: OpenShift Optional
    containerImage: ""
    createdAt: ""
    description: Fence Agents Remediation Operator for remediating nodes using upstream
      fence-agents.
    repository: https://github.com/medik8s/fence-agents-remediation
    support: Medik8s
  name: fence-agents-remediation.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FenceAgentsRemediation is the Schema for the fenceagentsremediations
        API
      displayName: Fence Agents Remediation
      kind: FenceAgentsRemediation
      name: fenceagentsremediations.fence-agents-remediation.medik8s.io
      resources:
      - kind: FenceAgentsRemediation
        name: fenceagentsremediations
        version: v1alpha1
      specDescriptors:
      - description: Agent is the type of fence agent that will be used
        displayName: Agent
        path: agent
      - description: NodeParameters are node specific they are passed to the fencing
          agent according to the node that is fenced
        displayName: Node Parameters
        path: nodeparameters
      - description: SharedParameters are passed to the fencing agent no matter which
          node is fenced (i.e they are common for all the nodes)
        displayName: Shared Parameters
        path: sharedparameters
      version: v1alpha1
    - description: FenceAgentsRemediationTemplate is the Schema for the fenceagentsremediationtemplates
        API
      displayName: Fence Agents Remediation Template
      kind: FenceAgentsRemediationTemplate
      name: fenceagentsremediationtemplates.fence-agents-remediation.medik8s.io
      resources:
      - kind: FenceAgentsRemediationTemplate
        name: fenceagentsremediationtemplates
        version: v1alpha1
      specDescriptors:
      - description: Template defines the desired state of FenceAgentsRemediationTemplate
        displayName: Template
        path: template
      - description: Agent is the type of fence agent that will be used
        displayName: Agent
        path: template.spec.agent
      - description: NodeParameters are node specific they are passed to the fencing
          agent according to the node that is fenced
        displayName: Node Parameters
        path: template.spec.nodeparameters
      - description: SharedParameters are passed to the fencing agent no matter which
          node is fenced (i.e they are common for all the nodes)
        displayName: Shared Parameters
        path: template.spec.sharedparameters
      version: v1alpha1
  description: Run existing set of upstream fencing agents for environments with a
    traditional API end-point (eg. IPMI) for power cycling cluster nodes.
  displayName: Fence Agents Remediation Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - medik8s
  - fencing
  - auto-healing
  - recovery
  - high-availability
  - fence-agents
  - fence-agents-remediation
  - remediation
  - far
  - baremetal
  links:
  - name: Fence Agents Remediation
    url: https://medik8s.io
  - name: Source Code
    url: https://github.com/medik8s/fence-agents-remediation
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  provider:
    name: Medik8s
    url: https://github.com/medik8s
  version: 0.0.0
