apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: OpenShift Optional
    containerImage: ""
    createdAt: ""
    description: Fence Agents Remediation Operator uses well-known agents to fence
      and remediate unhealthy nodes. The remediation includes rebooting the unhealthy
      node using a fence agent, and then evicting workloads from the unhealthy node.
    olm.skipRange: '>=0.0.1'
    repository: https://github.com/medik8s/fence-agents-remediation
    support: Medik8s
  name: fence-agents-remediation.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FenceAgentsRemediation is the Schema for the fenceagentsremediations
        API
      displayName: Fence Agents Remediation
      kind: FenceAgentsRemediation
      name: fenceagentsremediations.fence-agents-remediation.medik8s.io
      resources:
      - kind: FenceAgentsRemediation
        name: fenceagentsremediations
        version: v1alpha1
      specDescriptors:
      - description: Agent is the name of fence agent that will be used
        displayName: Agent
        path: agent
      - description: NodeParameters are passed to the fencing agent according to the
          node that is fenced, since they are node specific
        displayName: Node Parameters
        path: nodeparameters
      - description: SharedParameters are passed to the fencing agent regardless of
          which node is about to be fenced (i.e., they are common for all the nodes)
        displayName: Shared Parameters
        path: sharedparameters
      statusDescriptors:
      - description: 'Represents the observations of a FenceAgentsRemediation''s current
          state. Known .status.conditions.type are: "Processing", "FenceAgentActionSucceeded",
          and "Succeeded".'
        displayName: conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: LastUpdateTime is the last time the status was updated.
        displayName: Last Update Time
        path: lastUpdateTime
      version: v1alpha1
    - description: FenceAgentsRemediationTemplate is the Schema for the fenceagentsremediationtemplates
        API
      displayName: Fence Agents Remediation Template
      kind: FenceAgentsRemediationTemplate
      name: fenceagentsremediationtemplates.fence-agents-remediation.medik8s.io
      resources:
      - kind: FenceAgentsRemediationTemplate
        name: fenceagentsremediationtemplates
        version: v1alpha1
      specDescriptors:
      - description: Template defines the desired state of FenceAgentsRemediationTemplate
        displayName: Template
        path: template
      - description: Agent is the name of fence agent that will be used
        displayName: Agent
        path: template.spec.agent
      - description: NodeParameters are passed to the fencing agent according to the
          node that is fenced, since they are node specific
        displayName: Node Parameters
        path: template.spec.nodeparameters
      - description: SharedParameters are passed to the fencing agent regardless of
          which node is about to be fenced (i.e., they are common for all the nodes)
        displayName: Shared Parameters
        path: template.spec.sharedparameters
      version: v1alpha1
  description: |
    ### Introduction
    Fence Agents Remediation (FAR) is a Kubernetes operator that uses well-known agents to fence and remediate unhealthy nodes.
    The remediation includes rebooting the unhealthy node using a fence agent and then evicting workloads from the unhealthy node.

    ### Compatibility
    FAR is one of the remediator operators by [Medik8s](https://www.medik8s.io/remediation/remediation/),
    such as [Self Node Remediation](https://github.com/medik8s/self-node-remediation) and [Machine Deletion Remediation](https://github.com/medik8s/machine-deletion-remediation),
    that were designed to run with the Node HealthCheck Operator [(NHC)](https://github.com/medik8s/node-healthcheck-operator) which detects an unhealthy node and creates remediation CR.
    It is recommended to use FAR with NHC for an easier and smoother experience by fully automating the remediation process, but it can be used as a standalone remediator for the more experienced user.

    ### Advantages
    - Robustness - FAR has direct feedback from the traditional Application Programming Interface (API) call (e.g., IPMI) about the result of the fence action without using the Kubernetes API.
    - Speed - FAR is rapid since it can reboot a node and receive an acknowledgment from the API call while other remediators might need to wait a safe time till they can expect the node to be rebooted.
    - Diversity - FAR includes several fence agents from a large known set of upstream fencing agents for bare metal servers, virtual machines, cloud platforms, etc.
    - Adjustability - FAR allows to set up different parameters for running the API call that remediates the node.
  displayName: Fence Agents Remediation Operator
  icon:
  - base64data: base64EncodedIcon
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - medik8s
  - fencing
  - auto-healing
  - recovery
  - high-availability
  - fence-agents
  - fence-agents-remediation
  - remediation
  - far
  - baremetal
  links:
  - name: Fence Agents Remediation
    url: https://www.medik8s.io/remediation/fence-agents-remediation/fence-agents-remediation/
  - name: Source Code
    url: https://www.github.com/medik8s/fence-agents-remediation
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  minKubeVersion: 1.24.0
  provider:
    name: Medik8s
    url: https://github.com/medik8s
  version: 0.0.0
